version: '3'


services:
    db:
        image: postgres:15.6
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        container_name: blogdb
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - blog-network
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        networks:
            - blog-network

networks:
    blog-network:
        driver: bridge